version: "3.9"
services:
  next-lucia-auth:
    image: postgres
    restart: always
    container_name: next-lucia-auth
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: